# Конфигурация для модели эмбеддингов
model_name: "intfloat/multilingual-e5-large"
device: cpu
batch_size: 32
max_length: 256

# Параметры нормализации
normalize: true
pooling: mean

# Параметры чанкирования
chunking:
  enabled: true
  chunk_size: 500
  chunk_overlap: 50
